server:
  port: 8080



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/umr?serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: yswysyydxj

  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true




#  SpringBoot2.6版本和Swagger2.9.2不兼容
#  这个问题的主要原因确实是SpringBoot版本过高导致,如果你用的是SpringBoot2.5.x及之前版本是没有问题的。
#  Spring Boot 2.6.X使用PathPatternMatcher匹配路径，Swagger引用的Springfox使用的路径匹配是基于AntPathMatcher的。
#  所以要想解决，添加配置，将springBoot MVC的路径匹配模式修改一下即可
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

